Fix unit test compilation error: TimeoutInSeconds not implemented
nachocove/qa#707 is improved to the point where the unit tests compile
and run.  But they don't all pass.  I still need to look at the
failures.